# Groceteria Application Configuration
# Personal E-Commerce Project

# Server Configuration
server:
  port: 8080
  # Uncomment the line below to use a different port
  # port: 8085

# Database Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost/groceteria?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: Nakul123
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
    
    # Connection Pool Configuration
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

# OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    disable-swagger-default-url: true
    display-request-duration: true
    filter: true
    deep-linking: true
    display-operation-id: false
    syntax-highlight:
      activated: true
      theme: monokai
  
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

# Logging Configuration
logging:
  level:
    com.groceteria: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Application Information
info:
  app:
    name: Groceteria
    description: Personal E-Commerce Project
    version: 1.0.0
    author: Personal Project 